server:
  port: 8002

spring:
  application:
    name: mango-backup
  boot:
    admin:
      client:
        url: "http://localhost:8000"

management:
  endpoints:
    web:
      exposure:
        include: "*"

mango:
  backup:
    datasource:
      host: localhost
      username: root
      password: 1234qwer
      database: mango